import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-center bg-cover bg-[url('https://res.cloudinary.com/dah6xlxco/image/upload/v1772975218/ChatGPT_Image_Mar_8_2026_06_36_18_PM_masctk.png')]">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-2xl mx-auto">
        {children}
        </div>
      </div>
    </div>
      </body>
    </html>
  );
}
